FROM python:3.10-slim
WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY /ui/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY llm_integration/ ./llm_integration/
COPY /ui/ .

EXPOSE 8501

ENTRYPOINT ["streamlit", "run", "ui.py", "--server.port=8501", "--server.address=0.0.0.0"]